services:
  #this are the apps / container  i want to run
  #i choose postgres , but we can name it to any ,
  postgres:
    #postgres: databas software and leatest newest version
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=krisjson'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      #laptop and container port fot the postgreql
      - 5433:5432
  redis:
    image: 'redis:latest'
    ports:
      - 6380:6379

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/krisjson'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'
      - 'SPRING_DATA_REDIS_HOST=redis'
      - 'SPRING_DATA_REDIS_PORT=6379'

      #runs after the postgrs and redis
    depends_on:
      - postgres
      - redis


